fstNum = int(input("First Number :"))
sndNum = int(input("Second Number :"))
print(fstNum, "+", sndNum, "=", fstNum + sndNum)
print(fstNum, "-", sndNum, "=", fstNum - sndNum)
print(fstNum, "*", sndNum, "=", fstNum * sndNum)
print(fstNum, "/", sndNum, "=", fstNum / sndNum)
