scoreFoundationEnglish = float(80)
scoreGeneralBusiness = float(100)
scoreIntroduction2ComputerSystems = float(95)
scoreComputerProgramming = float(81.5)
print("--- Your Score ---")
print("Foundation English :", scoreFoundationEnglish)
print("General Business :", scoreGeneralBusiness)
print("Introduction to Computer Systems :", scoreIntroduction2ComputerSystems)
print("Computer Programming", scoreComputerProgramming)
