print("=======================")
print("=39's shop VAT INVOICE=")
print("=======================")
print("Apple      x", 3, 5, 3*5, "THB")
print("Orange     x", 1, 50, 1*50, "THB")
print("Grape      x", 5, 50, 5*50, "THB")
print("WaterMelon x", 1, 50, 1*50, "THB")
print("=======================")
print("TOTAL           ", 3*5+1*50+5*50+1*50, "THB")
print("=======================")
print("ThankYou PLZ Come again")
