print("=======================")
print("=39's shop VAT INVOICE=")
print("=======================")
print("Apple      x  3  15 THB")
print("Orange     x  1  50 THB")
print("Grape      x  5 250 THB")
print("WaterMelon x  1  50 THB")
print("Melon      x  2  70 THB")
print("CokeCan    x  1  15 THB")
print("FreshWater x 10 100 THB")
print("=======================")
print("TOTAL           550 THB")
print("=======================")
print("ThankYou PLZ Come again")